### Get my user id
GET https://api.twitch.tv/helix/users?login=sh0ckR6
Client-ID: 203znvm6i722pauvflk3d4bg2sh681
Authorization: Bearer 1b73dgo1trvje3ukvma0u7jhhtzrji

### Get app access token
POST https://id.twitch.tv/oauth2/token?client_id=203znvm6i722pauvflk3d4bg2sh681&client_secret=wy0fvzd0y28ijq50u45960pwbersmq&grant_type=client_credentials&scope=channel:manage:redemptions%20channel:read:redemptions%20channel:read:subscriptions

### Register follow eventsub handler
POST https://api.twitch.tv/helix/eventsub/subscriptions
Authorization: Bearer oafl91wppsqf0kwc2to15dmdf2gthw
Client-ID: 203znvm6i722pauvflk3d4bg2sh681
Content-Type: application/json

{
  "type": "channel.channel_points_custom_reward_redemption.add",
  "condition": {
    "broadcaster_user_id": "188494816"
  },
  "version": "1",
  "transport": {
    "method": "webhook",
    "callback": "https://ad91-174-88-150-110.ngrok.io/eventsub",
    "secret": "lmaopoggers"
  }
}

### Unregister follow eventsub handler
DELETE https://api.twitch.tv/helix/eventsub/subscriptions?id=7b039cce-e571-4d9a-80bb-00fbc8057b76
Authorization: Bearer oafl91wppsqf0kwc2to15dmdf2gthw
Client-ID: 203znvm6i722pauvflk3d4bg2sh681